create table asutused (
	id INT,
	Nimi VARCHAR(100),
	Asukoht VARCHAR(100),
	Keskmine hinne DECIMAL(2,1),
	Hinnatud (korda) DECIMAL(4,0)
);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (1, 'Kaks Kokka', 'Mere Puiestee 6E', 1.2, 14);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (2, 'Von Krahli Aed', 'Raekoja plats 8', 2.7, 52);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (3, 'Pegasus', 'Harju 1', 4.7, 66);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (4, 'Vana Toomase Restoran', 'Mustamäe tee', 6.4, 59);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (5, 'Tuljak', 'Pirita tee 26e', 9.6, 28);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (6, 'Kohvik Moon', 'Võrgu 3t', 6.6, 93);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (7, 'Bruxx', 'Rotermanni 2', 4.9, 26);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (8, 'Pegasus', 'Paldiski mnt', 7.4, 14);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (9, 'Ö', 'Mere puiestee 6e', 9.6, 97);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (10, 'Olde hansa', 'Vana turg 1', 9.5, 20);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (11, 'Rataskaevu 16', 'Ratasekaevu 16', 4.5, 23);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (12, 'Kogu resto ja Pagar', 'Võrgu tn 6', 7.7, 5);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (13, 'Pegasus', 'Vabaduse puiestee', 1.9, 11);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (14, 'F-Hoone', 'Telliskivi 60a', 2.5, 88);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (15, 'F-Hoone', 'Pärnu mnt', 4.4, 63);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (16, 'Rataskaevu 16', 'Tartu maantee', 3.5, 61);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (17, 'Ö', 'Laagna tee', 6.9, 83);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (18, 'Kaks Kokka', 'Rannamäe tee', 2.1, 47);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (19, 'Ö', 'Pärnu mnt', 2.4, 44);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (20, 'F-Hoone', 'Tartu maantee', 4.5, 76);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (21, 'F-Hoone', 'Vabaduse puiestee', 9.3, 49);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (22, 'Kaks Kokka', 'Paldiski mnt', 1.5, 37);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (23, 'F-Hoone', 'Rannamäe tee', 7.3, 13);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (24, 'Rataskaevu 16', 'Mustamäe tee', 10.0, 69);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (25, 'Kohvik Moon', 'Rannamäe tee', 3.8, 71);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (26, 'Kohvik Moon', 'Tallinna tee', 1.9, 49);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (27, 'Pegasus', 'Vabaduse puiestee', 2.3, 41);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (28, 'Von Krahli Aed', 'Narva maantee', 4.2, 91);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (29, 'Tuljak', 'Vabaduse puiestee', 4.2, 17);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (30, 'F-Hoone', 'Narva maantee', 5.7, 70);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (31, 'Kaks Kokka', 'Narva maantee', 5.0, 30);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (32, 'Kohvik Moon', 'Laagna tee', 5.2, 34);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (33, 'Kohvik Moon', 'Paldiski mnt', 3.7, 73);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (34, 'Pegasus', 'Tallinna tee', 4.4, 2);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (35, 'Ö', 'Pärnu mnt', 6.8, 65);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (36, 'F-Hoone', 'Mustamäe tee', 1.2, 45);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (37, 'Tuljak', 'Peterburi tee', 10.0, 1);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (38, 'NOA', 'Laagna tee', 9.8, 33);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (39, 'Kaks Kokka', 'Rannamäe tee', 8.1, 63);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (40, 'Kohvik Moon', 'Pärnu mnt', 3.1, 43);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (41, 'Ö', 'Vabaduse puiestee', 3.6, 74);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (42, 'NOA', 'Rannamäe tee', 9.8, 25);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (43, 'Leib Resto ja Aed', 'Peterburi tee', 3.1, 89);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (44, 'Rataskaevu 16', 'Mustamäe tee', 5.4, 5);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (45, 'Tuljak', 'Mustamäe tee', 9.8, 1);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (46, 'Ö', 'Tallinna tee', 8.6, 8);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (47, 'Leib Resto ja Aed', 'Tartu maantee', 9.1, 13);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (48, 'Rataskaevu 16', 'Laagna tee', 1.2, 92);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (49, 'Kaks Kokka', 'Peterburi tee', 2.8, 33);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (50, 'NOA', 'Narva maantee', 3.3, 5);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (51, 'Tuljak', 'Peterburi tee', 3.4, 72);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (52, 'Pegasus', 'Peterburi tee', 6.1, 24);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (53, 'F-Hoone', 'Mustamäe tee', 4.1, 71);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (54, 'Von Krahli Aed', 'Peterburi tee', 6.7, 1);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (55, 'Pegasus', 'Peterburi tee', 7.8, 43);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (56, 'Pegasus', 'Peterburi tee', 1.8, 26);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (57, 'Tuljak', 'Narva maantee', 4.2, 5);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (58, 'Kaks Kokka', 'Pärnu mnt', 9.2, 69);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (59, 'Tuljak', 'Laagna tee', 9.9, 85);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (60, 'Pegasus', 'Tartu maantee', 1.4, 50);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (61, 'Ö', 'Narva maantee', 8.5, 48);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (62, 'Tuljak', 'Narva maantee', 8.4, 2);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (63, 'Ö', 'Tartu maantee', 8.7, 99);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (64, 'Pegasus', 'Narva maantee', 4.6, 21);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (65, 'Leib Resto ja Aed', 'Mustamäe tee', 5.9, 6);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (66, 'Rataskaevu 16', 'Tartu maantee', 9.8, 83);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (67, 'Tuljak', 'Laagna tee', 1.1, 92);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (68, 'Tuljak', 'Mustamäe tee', 2.7, 79);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (69, 'NOA', 'Vabaduse puiestee', 3.0, 34);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (70, 'Leib Resto ja Aed', 'Peterburi tee', 8.4, 54);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (71, 'Pegasus', 'Paldiski mnt', 7.7, 25);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (72, 'NOA', 'Tartu maantee', 3.7, 88);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (73, 'Von Krahli Aed', 'Paldiski mnt', 3.9, 13);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (74, 'NOA', 'Rannamäe tee', 4.8, 86);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (75, 'Kaks Kokka', 'Paldiski mnt', 8.4, 46);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (76, 'Leib Resto ja Aed', 'Peterburi tee', 2.9, 99);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (77, 'Von Krahli Aed', 'Rannamäe tee', 2.1, 90);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (78, 'NOA', 'Pärnu mnt', 4.8, 63);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (79, 'Kaks Kokka', 'Tallinna tee', 5.5, 86);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (80, 'Rataskaevu 16', 'Rannamäe tee', 1.8, 48);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (81, 'Kaks Kokka', 'Peterburi tee', 6.1, 70);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (82, 'Rataskaevu 16', 'Peterburi tee', 2.7, 69);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (83, 'Tuljak', 'Narva maantee', 9.5, 51);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (84, 'F-Hoone', 'Vabaduse puiestee', 8.7, 84);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (85, 'Kaks Kokka', 'Peterburi tee', 2.7, 34);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (86, 'Tuljak', 'Vabaduse puiestee', 4.7, 97);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (87, 'Pegasus', 'Tallinna tee', 7.8, 8);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (88, 'Kaks Kokka', 'Narva maantee', 6.0, 35);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (89, 'F-Hoone', 'Rannamäe tee', 4.2, 80);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (90, 'NOA', 'Narva maantee', 6.7, 31);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (91, 'F-Hoone', 'Pärnu mnt', 3.3, 99);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (92, 'Kohvik Moon', 'Tallinna tee', 7.4, 49);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (93, 'Von Krahli Aed', 'Pärnu mnt', 3.8, 28);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (94, 'Von Krahli Aed', 'Pärnu mnt', 5.0, 71);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (95, 'Kohvik Moon', 'Rannamäe tee', 7.1, 9);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (96, 'Pegasus', 'Rannamäe tee', 7.4, 29);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (97, 'Tuljak', 'Tartu maantee', 2.4, 34);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (98, 'Kohvik Moon', 'Mustamäe tee', 3.8, 10);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (99, 'Kohvik Moon', 'Pärnu mnt', 3.4, 65);
insert into asutused (id, Nimi, Asukoht, Keskmine hinne, Hinnatud (korda)) values (100, 'Ö', 'Tartu maantee', 1.0, 40);